/**
 * Seed a demo account with a realistic, imperfect record.
 *
 * The record itself is generated by `src/lib/demo-record.ts`, which the
 * standalone demo page also bundles — one source, so the page you can open in
 * a browser and the account you can sign into show the same thing.
 *
 * Run:  npm run seed
 */

import { randomUUID } from 'node:crypto'
import { eq } from 'drizzle-orm'
import { db, migrate, schema, sqlClient } from '../src/lib/db/client'
import { hashPassword } from '../src/lib/auth'
import { buildDemoRecord, DEMO_EMAIL, DEMO_NAME, DEMO_PASSWORD } from '../src/lib/demo-record'
import { todayKey } from '../src/lib/pedr/week'

async function main() {
  await migrate()

  const existing = await db.select().from(schema.users).where(eq(schema.users.email, DEMO_EMAIL)).limit(1)
  if (existing[0]) {
    // Start clean, so re-running the seed is idempotent.
    await db.delete(schema.users).where(eq(schema.users.id, existing[0].id))
  }

  const userId = randomUUID()
  const record = buildDemoRecord({ today: todayKey(), userId, id: () => randomUUID() })
  const stamp = new Date().toISOString()

  await db.insert(schema.users).values({
    id: userId,
    email: DEMO_EMAIL,
    name: DEMO_NAME,
    passwordHash: await hashPassword(DEMO_PASSWORD),
    teamsName: DEMO_NAME,
    calendarToken: 'demo-calendar-token',
    experienceStart: record.experienceStart,
    targetExamDate: record.targetExamDate,
    createdAt: stamp,
  })

  await db.insert(schema.employments).values({ ...record.employment, userId })

  for (const project of record.projects) {
    await db.insert(schema.projects).values({ ...project, userId })
  }

  for (let i = 0; i < record.entries.length; i += 50) {
    await db.insert(schema.entries).values(
      record.entries.slice(i, i + 50).map((entry) => ({
        ...entry,
        userId,
        // Stored as an integer percentage, not a fraction.
        confidence: Math.round(entry.confidence * 100),
      })),
    )
  }
  for (let i = 0; i < record.notes.length; i += 50) {
    await db.insert(schema.weekNotes).values(
      record.notes.slice(i, i + 50).map((note) => ({ ...note, userId })),
    )
  }

  console.log(`Seeded ${DEMO_EMAIL} / ${DEMO_PASSWORD}`)
  console.log(`  ${record.entries.length} entries, ${record.notes.length} week notes`)
  console.log(`  experience starts ${record.experienceStart}`)
}

main().then(
  async () => { sqlClient.close(); process.exit(0) },
  (error) => { console.error(error); process.exit(1) },
)
